# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmds.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import state_pb2 as state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmds.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncmds.proto\x1a\x0bstate.proto\"\'\n\x0bSteeringCmd\x12\x18\n\x10steeringSetPoint\x18\x01 \x02(\x05\"!\n\x08SpeedCmd\x12\x15\n\rspeedSetPoint\x18\x01 \x02(\x05\"J\n\x0bWaypointCmd\x12\x11\n\tlongitude\x18\x01 \x02(\t\x12\x10\n\x08latitude\x18\x02 \x02(\t\x12\x16\n\x0esequenceNumber\x18\x03 \x02(\x05\"&\n\x08\x42\x61sicCmd\x12\x1a\n\x08\x62\x61sicCmd\x18\x01 \x02(\x0e\x32\x08.CmdType\"\x80\x01\n\x11ManualControlCmds\x12\x18\n\x10steeringSetPoint\x18\x01 \x02(\x05\x12\x15\n\rspeedSetPoint\x18\x02 \x02(\x05\x12\x1e\n\x0bsetCarState\x18\x03 \x02(\x0e\x32\t.CarState\x12\x1a\n\x08\x42\x61sicCmd\x18\x04 \x02(\x0e\x32\x08.CmdType\"*\n\x08StateCmd\x12\x1e\n\x0bsetCarState\x18\x01 \x02(\x0e\x32\t.CarState\"\x1c\n\x08\x44\x65\x62ugCmd\x12\x10\n\x08\x64\x65\x62ugCmd\x18\x01 \x02(\x05*\x13\n\x07\x43mdType\x12\x08\n\x04STOP\x10\x00'
  ,
  dependencies=[state__pb2.DESCRIPTOR,])

_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='CmdType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=424,
  serialized_end=443,
)
_sym_db.RegisterEnumDescriptor(_CMDTYPE)

CmdType = enum_type_wrapper.EnumTypeWrapper(_CMDTYPE)
STOP = 0



_STEERINGCMD = _descriptor.Descriptor(
  name='SteeringCmd',
  full_name='SteeringCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='steeringSetPoint', full_name='SteeringCmd.steeringSetPoint', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=66,
)


_SPEEDCMD = _descriptor.Descriptor(
  name='SpeedCmd',
  full_name='SpeedCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='speedSetPoint', full_name='SpeedCmd.speedSetPoint', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=101,
)


_WAYPOINTCMD = _descriptor.Descriptor(
  name='WaypointCmd',
  full_name='WaypointCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='WaypointCmd.longitude', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='WaypointCmd.latitude', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequenceNumber', full_name='WaypointCmd.sequenceNumber', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=177,
)


_BASICCMD = _descriptor.Descriptor(
  name='BasicCmd',
  full_name='BasicCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='basicCmd', full_name='BasicCmd.basicCmd', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=217,
)


_MANUALCONTROLCMDS = _descriptor.Descriptor(
  name='ManualControlCmds',
  full_name='ManualControlCmds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='steeringSetPoint', full_name='ManualControlCmds.steeringSetPoint', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speedSetPoint', full_name='ManualControlCmds.speedSetPoint', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setCarState', full_name='ManualControlCmds.setCarState', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BasicCmd', full_name='ManualControlCmds.BasicCmd', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=348,
)


_STATECMD = _descriptor.Descriptor(
  name='StateCmd',
  full_name='StateCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='setCarState', full_name='StateCmd.setCarState', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=392,
)


_DEBUGCMD = _descriptor.Descriptor(
  name='DebugCmd',
  full_name='DebugCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='debugCmd', full_name='DebugCmd.debugCmd', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=422,
)

_BASICCMD.fields_by_name['basicCmd'].enum_type = _CMDTYPE
_MANUALCONTROLCMDS.fields_by_name['setCarState'].enum_type = state__pb2._CARSTATE
_MANUALCONTROLCMDS.fields_by_name['BasicCmd'].enum_type = _CMDTYPE
_STATECMD.fields_by_name['setCarState'].enum_type = state__pb2._CARSTATE
DESCRIPTOR.message_types_by_name['SteeringCmd'] = _STEERINGCMD
DESCRIPTOR.message_types_by_name['SpeedCmd'] = _SPEEDCMD
DESCRIPTOR.message_types_by_name['WaypointCmd'] = _WAYPOINTCMD
DESCRIPTOR.message_types_by_name['BasicCmd'] = _BASICCMD
DESCRIPTOR.message_types_by_name['ManualControlCmds'] = _MANUALCONTROLCMDS
DESCRIPTOR.message_types_by_name['StateCmd'] = _STATECMD
DESCRIPTOR.message_types_by_name['DebugCmd'] = _DEBUGCMD
DESCRIPTOR.enum_types_by_name['CmdType'] = _CMDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SteeringCmd = _reflection.GeneratedProtocolMessageType('SteeringCmd', (_message.Message,), {
  'DESCRIPTOR' : _STEERINGCMD,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:SteeringCmd)
  })
_sym_db.RegisterMessage(SteeringCmd)

SpeedCmd = _reflection.GeneratedProtocolMessageType('SpeedCmd', (_message.Message,), {
  'DESCRIPTOR' : _SPEEDCMD,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:SpeedCmd)
  })
_sym_db.RegisterMessage(SpeedCmd)

WaypointCmd = _reflection.GeneratedProtocolMessageType('WaypointCmd', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINTCMD,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:WaypointCmd)
  })
_sym_db.RegisterMessage(WaypointCmd)

BasicCmd = _reflection.GeneratedProtocolMessageType('BasicCmd', (_message.Message,), {
  'DESCRIPTOR' : _BASICCMD,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:BasicCmd)
  })
_sym_db.RegisterMessage(BasicCmd)

ManualControlCmds = _reflection.GeneratedProtocolMessageType('ManualControlCmds', (_message.Message,), {
  'DESCRIPTOR' : _MANUALCONTROLCMDS,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:ManualControlCmds)
  })
_sym_db.RegisterMessage(ManualControlCmds)

StateCmd = _reflection.GeneratedProtocolMessageType('StateCmd', (_message.Message,), {
  'DESCRIPTOR' : _STATECMD,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:StateCmd)
  })
_sym_db.RegisterMessage(StateCmd)

DebugCmd = _reflection.GeneratedProtocolMessageType('DebugCmd', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGCMD,
  '__module__' : 'cmds_pb2'
  # @@protoc_insertion_point(class_scope:DebugCmd)
  })
_sym_db.RegisterMessage(DebugCmd)


# @@protoc_insertion_point(module_scope)
