# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import state_pb2 as state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftelemetry.proto\x1a\x0bstate.proto\"r\n\x0e\x42\x61sicTelemetry\x12\x1b\n\x08\x63\x61rState\x18\x01 \x02(\x0e\x32\t.CarState\x12\r\n\x05speed\x18\x02 \x02(\x02\x12\x0f\n\x07heading\x18\x03 \x02(\x02\x12\x11\n\tlongitude\x18\x04 \x02(\t\x12\x10\n\x08latitude\x18\x05 \x02(\t\" \n\x11\x45xpandedTelemetry\x12\x0b\n\x03tmp\x18\x01 \x02(\x05\"\"\n\x0b\x44\x65\x62ugStatus\x12\x13\n\x0b\x64\x65\x62ugStatus\x18\x01 \x02(\x05'
  ,
  dependencies=[state__pb2.DESCRIPTOR,])




_BASICTELEMETRY = _descriptor.Descriptor(
  name='BasicTelemetry',
  full_name='BasicTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='carState', full_name='BasicTelemetry.carState', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='BasicTelemetry.speed', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='BasicTelemetry.heading', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='BasicTelemetry.longitude', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='BasicTelemetry.latitude', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=146,
)


_EXPANDEDTELEMETRY = _descriptor.Descriptor(
  name='ExpandedTelemetry',
  full_name='ExpandedTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tmp', full_name='ExpandedTelemetry.tmp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=180,
)


_DEBUGSTATUS = _descriptor.Descriptor(
  name='DebugStatus',
  full_name='DebugStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='debugStatus', full_name='DebugStatus.debugStatus', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=216,
)

_BASICTELEMETRY.fields_by_name['carState'].enum_type = state__pb2._CARSTATE
DESCRIPTOR.message_types_by_name['BasicTelemetry'] = _BASICTELEMETRY
DESCRIPTOR.message_types_by_name['ExpandedTelemetry'] = _EXPANDEDTELEMETRY
DESCRIPTOR.message_types_by_name['DebugStatus'] = _DEBUGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BasicTelemetry = _reflection.GeneratedProtocolMessageType('BasicTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _BASICTELEMETRY,
  '__module__' : 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:BasicTelemetry)
  })
_sym_db.RegisterMessage(BasicTelemetry)

ExpandedTelemetry = _reflection.GeneratedProtocolMessageType('ExpandedTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _EXPANDEDTELEMETRY,
  '__module__' : 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:ExpandedTelemetry)
  })
_sym_db.RegisterMessage(ExpandedTelemetry)

DebugStatus = _reflection.GeneratedProtocolMessageType('DebugStatus', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGSTATUS,
  '__module__' : 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:DebugStatus)
  })
_sym_db.RegisterMessage(DebugStatus)


# @@protoc_insertion_point(module_scope)
