/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Mar 27 13:47:19 2019. */

#include "cmds.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SteeringCmd_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SteeringCmd, steeringSetPoint, steeringSetPoint, 0),
    PB_LAST_FIELD
};

const pb_field_t SpeedCmd_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SpeedCmd, speedSetPoint, speedSetPoint, 0),
    PB_LAST_FIELD
};

const pb_field_t WaypointCmd_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, WaypointCmd, longitude, longitude, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, WaypointCmd, latitude, longitude, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, WaypointCmd, sequenceNumber, latitude, 0),
    PB_LAST_FIELD
};

const pb_field_t BasicCmd_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, BasicCmd, cmdType, cmdType, 0),
    PB_LAST_FIELD
};

const pb_field_t DebugCmd_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DebugCmd, debugCmd, debugCmd, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
