/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Wed Apr 10 11:45:02 2019. */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#include "state.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Log {
    pb_callback_t logMsg;
/* @@protoc_insertion_point(struct:Log) */
} Log;

typedef struct _BasicTelemetry {
    CarState carState;
    float speed;
    float heading;
    pb_callback_t longitude;
    pb_callback_t latitude;
/* @@protoc_insertion_point(struct:BasicTelemetry) */
} BasicTelemetry;

typedef struct _DebugStatus {
    int32_t debugStatus;
/* @@protoc_insertion_point(struct:DebugStatus) */
} DebugStatus;

typedef struct _ExpandedTelemetry {
    int32_t tmp;
/* @@protoc_insertion_point(struct:ExpandedTelemetry) */
} ExpandedTelemetry;

/* Default values for struct fields */

/* Initializer values for message structs */
#define BasicTelemetry_init_default              {_CarState_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ExpandedTelemetry_init_default           {0}
#define Log_init_default                         {{{NULL}, NULL}}
#define DebugStatus_init_default                 {0}
#define BasicTelemetry_init_zero                 {_CarState_MIN, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define ExpandedTelemetry_init_zero              {0}
#define Log_init_zero                            {{{NULL}, NULL}}
#define DebugStatus_init_zero                    {0}

/* Field tags (for use in manual encoding/decoding) */
#define Log_logMsg_tag                           1
#define BasicTelemetry_carState_tag              1
#define BasicTelemetry_speed_tag                 2
#define BasicTelemetry_heading_tag               3
#define BasicTelemetry_longitude_tag             4
#define BasicTelemetry_latitude_tag              5
#define DebugStatus_debugStatus_tag              1
#define ExpandedTelemetry_tmp_tag                1

/* Struct field encoding specification for nanopb */
extern const pb_field_t BasicTelemetry_fields[6];
extern const pb_field_t ExpandedTelemetry_fields[2];
extern const pb_field_t Log_fields[2];
extern const pb_field_t DebugStatus_fields[2];

/* Maximum encoded size of messages (where known) */
/* BasicTelemetry_size depends on runtime parameters */
#define ExpandedTelemetry_size                   11
/* Log_size depends on runtime parameters */
#define DebugStatus_size                         11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TELEMETRY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
