/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Apr  8 13:50:01 2019. */

#include "telemetry.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t BasicTelemetry_fields[6] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, BasicTelemetry, carState, carState, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, BasicTelemetry, speed, carState, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, BasicTelemetry, heading, speed, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, BasicTelemetry, longitude, heading, 0),
    PB_FIELD(  5, STRING  , REQUIRED, CALLBACK, OTHER, BasicTelemetry, latitude, longitude, 0),
    PB_LAST_FIELD
};

const pb_field_t ExpandedTelemetry_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ExpandedTelemetry, tmp, tmp, 0),
    PB_LAST_FIELD
};

const pb_field_t DebugStatus_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DebugStatus, debugStatus, debugStatus, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
