/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Apr 10 11:45:02 2019. */

#include "state.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif





/* @@protoc_insertion_point(eof) */
